language: node_js
node_js:
- 4
env:
  global:
  - GIT_NAME: Travis
  - GIT_EMAIL: tech@jincor.com
  - GITHUB_REPO: JincorTech/wiki
  - GIT_SOURCE: _docpress
script:
- yarn
- yarn build
after_success:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then ./node_modules/.bin/git-update-ghpages
  -e; fi
