language: node_js
node_js:
- 4
env:
  global:
  - GIT_NAME: Amazing-Space-Invader
  - GIT_EMAIL: amazing.space.invader@gmail.com
  - GITHUB_REPO: JincorTech/wiki
  - GIT_SOURCE: _docpress
  - secure: ZyTYVv/3ExD4hDPea5OYya940v1CuGz8uzSs1aHLGeJ0NhBSje8KO2OwnZu6L1mOyjHJdTRYsaeSNjd9egoATMdVM2fASXxvxXk0AsKWtGisw1T9g37mceGSWNN4IfNe+WvK+YNB60fXZmqQBl8jIwFCLhS9E1mXYiYyNHWPdwXPgVvAXD7z7nktslLM/QeQbFTDi4qUfiIZyeSvNyblbXc4PfIPttuT4xO8KA3bVN0MCxJUAnsxbJLDrXKqXIvO9p9jypaURZLsnrl4Sx3mqLhaD/LnR1tcy1DaplnYq5OnNKCrzqf/2B4y45DgqHvvgkNgTCw1VLtqFfjKHGPjdMKI+N7oWYHIIxwfjCxkQxzPyl1iguTrOcl4cb2tIvP5KFlLObDG2yBQQU1IDWV5ZRY58WtAaFh6MGy4+pcTaaNV3ho5XpGegzUPIk13NaVmrquFRzzFu7UVv9U4bwX0nr72Pm/oYS3M+A6JiscjN6iGtBfFMV1DHhGtQjfk9TVRUL/SI8KlapNJL0j2lphlVwZPOsUTJhDwRP0yr+k6QVVslHETTZljgAt3m5hw/IfNOOUbxuINN0VZ9qmO2yGOi/acba2ivEK6jb1gLOVolbyMH3xSoxrMriFBFfGB0Xz/lZv54vsnDuz/W1wXtryh6b1Oog3J+RwK/T1Le7BkD7Y=
script:
- yarn
- yarn build
after_success:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then ./node_modules/.bin/git-update-ghpages
  -e; fi
